### ISSUE TITLE
Any binary releases availble for Windows x64?

### ISSUE THREAD

**Issue by acotty** [lhak/Dependencies#1]
This fork has had allot of work done. There are no binaries in the release area. 

Are there any binaries available?

**Comment by lhak** [comment]
I have generated and uploaded binaries from the windowsappsdk (for x64) and windowsappsdk_arm64 (for arm64) branches. Please give it a try.

**Comment by acotty** [comment]
My quick 2 minutes test on Win11 x64 with MSYS2 x64 app worked. Thanks very much.

**Comment by asmwarrior** [comment]
I just found that the [lucasg/Dependencies](https://github.com/lucasg/Dependencies) does not work correctly on some Windows OS, but your version works, thanks!!!
