### ISSUE TITLE
Add option to show only missing dependencies

### ISSUE THREAD

**Issue by ThiloteE** [lhak/Dependencies#4]
Hello Ihak, I am on Windows 10 with 32GB RAM.

I used Dependencies to check a torch_cuda.dll (\~ 900mb) for missing dependencies, but there are sooo many dependencies in that file, that it is hard to come up with a comprehensive list of dependencies that are missing.

My current approach is to set "recursively" in the settings and expand all items and then to sort the list by checksum, which also shows the missing ones, but then selecting the dependencies has led to the app crashing twice now (task manager showed there is still lots of RAM available). I am attempting again, but loading this long list of item takes a long time, so I was thinking of what I could do in the meantime and here I am :D

I want to select the list of items (only the missing dependencies) to copy and paste them into a text file, because I need this data to report a bug.

**Comment by lhak** [comment]
I currently do not plan to do any major feature work on this application. The WPF version actually has a window showing the module loading order, but that also only shows the modules that were already loaded. So in the name of parity, I implemented similar functionality. However, in this version it actively scans for all dependencies of a module. Copying the list of dependencies (all or only those missing) is also possible. A test release is available here:

https://github.com/lhak/Dependencies/releases/tag/241204-test

The functionality is available in the context menu of the modules in the tree view.

**Comment by lhak** [comment]
This functionality is now available in the latest release

**Comment by ThiloteE** [comment]
Oh my god, I totally forgot to answer you. Thank you so much for your effort. I am sure, this will help a lot of people <3

**Comment by ThiloteE** [comment]
Meanwhile, I found out why I had so many dependencies that were missing that it crashed the app, lol. I had multiple cuda installed on my system and the one that was required was not set to "PATH" in Windows Environment Variables. I am so sorry, to have made you work on this for my sake, but I am sure, it will come in handy in the mid/long term for other people and maybe yourself too.
